services:
  way2rome:
    build: .
    ports:
      - 1006:3000
    restart: always
    healthcheck:
      test: socat - TCP4:localhost:3000 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
